### ISSUE TITLE
[bug] When non Windows (Like a Linux) OS, generate server.properties incorrect path

### ISSUE THREAD

**Issue by falconws** [jaideepsinghheer/MinecraftForge-Mods-ServerPropertiesLAN#1]
https://github.com/jaideepsinghheer/MinecraftForge-Mods-ServerPropertiesLAN/blob/79bf51f6dfdcde9817528eea15d985a911468ccf/src/main/java/JaideepSinghHeer/Minecraft/mod/ServerPropertiesLAN.java#L130

This code generate saves/[world_name]\server.properties.
Server config file name is "[world_name]\server.properties".

Should be generate saves/[world_name]/server.properties.
Different is directory path separator character "/" or "\\".

Sorry my poor English.

**Comment by jaideepsinghheer** [comment]
**Bug fixed** ...! Thanx for reporting it. Please close the issue when confirmed.

**Comment by falconws** [comment]
Thank you fix this bug.
I confirmed it Linux mint 17.3 MATE.
confirmed version is Server.Properties for LAN v2.5-1.8.9+.

And... Thank you very much this **GREAT** convenient mod !!
Close issue.
